// Auto-generated by Embedded IDE
// MCU: STM32F103C8Tx | HAL: stm32f1xx-hal

#![no_std]
#![no_main]

mod pins;
use cortex_m_rt::entry;
use panic_halt as _;

mod mw_radar;
use mw_radar::utils::*;
use mw_radar::read::ParserResult;


// <<< GENERATED BEGIN — do not edit between these markers >>>
use stm32f1xx_hal::{
    pac,
    prelude::*,
};

#[entry]
fn main() -> ! {
let dp = pac::Peripherals::take().unwrap();

let mut flash = dp.FLASH.constrain();
let rcc = dp.RCC.constrain();
let mut afio = dp.AFIO.constrain();
let clocks = rcc.cfgr
                 .sysclk(8.MHz())
                 .pclk1(4.MHz())
                 .freeze(&mut flash.acr);

    let mut gpioa = dp.GPIOA.split();
    let mut gpiob = dp.GPIOB.split();
    let mut gpioc = dp.GPIOC.split();

    // ── Port A ──
    let pa10_usart1_rx = gpioa.pa10.into_floating_input(&mut gpioa.crh); // USART1  RX
    let pa9_usart1_tx = gpioa.pa9.into_alternate_push_pull(&mut gpioa.crh); // USART1  TX

    // ── Port B ──
    let pb9_i2c1_sda = gpiob.pb9.into_alternate_open_drain(&mut gpiob.crh); // I2C1  SDA
    let pb8_i2c1_scl = gpiob.pb8.into_alternate_open_drain(&mut gpiob.crh); // I2C1  SCL
    let pb5_in_mw_ot2 = gpiob.pb5.into_floating_input(&mut gpiob.crl); // GPIO Input

    // ── Port C ──
    let pc13_out_board_led = &mut gpioc.pc13.into_push_pull_output(&mut gpioc.crh); // GPIO Output

    // ── Peripheral initialisation ──
    let (mut _tx1_mw_radar, mut _rx1_mw_radar) = pins::configs::usart1::init(dp.USART1, (pa9_usart1_tx, pa10_usart1_rx), &mut afio, &clocks);
    let _i2c1_128x32_display = pins::configs::i2c1::init(dp.I2C1, (pb8_i2c1_scl, pb9_i2c1_sda), &mut afio, &clocks);

// <<< GENERATED END >>>

    let delay_ms = &|ms:u32|{
        cortex_m::asm::delay(ms.saturating_mul(&clocks.sysclk().to_Hz() / 1_000));
    };



    pc13_out_board_led.set_high();


    let mut display = pins::utils::i2c1::get_display_128x32(_i2c1_128x32_display);

    /**/

    pins::utils::i2c1::clear_display(&mut display);

    //pins::utils::i2c1::wtrite_to_display(&mut display,"HMMD mmWave", 0);
    // pins::utils::i2c1::wtrite_to_display(&mut display,"Waiting...", 11);
    //display.flush().unwrap();


    //----------------------
    let mut parser_params = mw_radar::read_param::ReadParam::new_parser();
    //----------------------

    begin_config(&mut _tx1_mw_radar,&mut _rx1_mw_radar,delay_ms);
    {
        let radar_range_gate_val:Option<u32> = mw_radar::utils::get_param_value(
            &mut _tx1_mw_radar,&mut _rx1_mw_radar
            ,mw_radar::data::ParameterID::Range
            ,&mut parser_params
            ,delay_ms
        );


        let mut out = [0u8; 32]; 

        pins::utils::i2c1::wtrite_to_display(&mut display
            ,format_text_with_u32("Range: ",radar_range_gate_val.unwrap_or_default(), "", &mut out)
            ,0);
    }
    //----------------------
    {
        let radar_delay_gate_val:Option<u32> = mw_radar::utils::get_param_value(
            &mut _tx1_mw_radar,&mut _rx1_mw_radar
            ,mw_radar::data::ParameterID::Delay
            ,&mut parser_params
            ,delay_ms
        );

        let mut out = [0u8; 32];

        pins::utils::i2c1::wtrite_to_display(&mut display
            ,format_text_with_u32("Delay: ",radar_delay_gate_val.unwrap_or_default(), " sec", &mut out)
            ,11);
    }



    // pins::utils::i2c1::wtrite_to_display(&mut display
    // ,format_text_with_u32_2inline(
    // "Range=",decode(radar_tt_00_val.unwrap_or_default())
    // ," Delay=",decode(radar_ht_00_val.unwrap_or_default())
    // , &mut out)
    // ,22);

    //----------------------
    {
        let radar_tt_00_val:Option<u32> = mw_radar::utils::get_param_value(
            &mut _tx1_mw_radar,&mut _rx1_mw_radar
            ,mw_radar::data::ParameterID::TriggerThreshold00
            ,&mut parser_params
            ,delay_ms
        );

        let radar_ht_00_val:Option<u32> = mw_radar::utils::get_param_value(
            &mut _tx1_mw_radar,&mut _rx1_mw_radar
            ,mw_radar::data::ParameterID::HoldThreshold00
            ,&mut parser_params
            ,delay_ms
        );


        let mut out = [0u8; 32];

        pins::utils::i2c1::wtrite_to_display(&mut display
            ,format_text_with_u32_2inline(
                "00 tt=",decode_threschold_value(radar_tt_00_val.unwrap_or_default())
                ," ht=",decode_threschold_value(radar_ht_00_val.unwrap_or_default())
                , &mut out)
            ,22);
    }

    display.flush().unwrap();


    delay_ms(10000);

    end_save_config(&mut _tx1_mw_radar,&mut _rx1_mw_radar,delay_ms);

    // cortex_m::asm::delay(999_999_999);//72MHz
    // ── Loop principal ────────────────────────────────────────────────────────


    let radar_range_gate:u32 = 0;//0-15 * 70cm
    let radar_delay_sec:u32 = 2; // 1 - 999 999 99



    send_config(&mut _tx1_mw_radar,&mut _rx1_mw_radar, radar_range_gate as f32 , radar_delay_sec as f32, 48.93,delay_ms);





    let mut buf_a:  [u8; 10]  = [0; 10];
    let mut lbuf:  [u8; 24] = [0; 24];
    //let mut buf_b:  [u8; 8]  = [0; 8];

    let mut parser = mw_radar::read_report::HmmdFrame::new_parser();
    loop {

        if pb5_in_mw_ot2.is_high(){
            pc13_out_board_led.set_low();
        }else{
            pc13_out_board_led.set_high();
        }


        if let Ok(b) = _rx1_mw_radar.read() {

            if parser.feed(b) {
                let frame = mw_radar::read_report::HmmdFrame::decode(&parser.payload);
                // ── Render display ────────────────────────────────────────────
                pins::utils::i2c1::clear_display(&mut display);
                // Rand 0 (y=0): "PREZENT" / "ABSENT " + distanta filtrata
                // ex: "PREZENT 245cm"
                {
                    let mut pos = 0usize;

                    pins::utils::i2c1::wtrite_to_display(&mut display,
                        if frame.present { "PREZENT" } else { "ABSENT" }
                        , 0);

                    //for &c in status { lbuf[pos] = c; pos += 1; }
                    if frame.present {
                        let sd = fmt_u16(frame.distance_cm, &mut buf_a);
                        for &c in sd.as_bytes() { lbuf[pos] = c; pos += 1; }
                        for &c in b"cm" { lbuf[pos] = c; pos += 1; }
                    }
                    pins::utils::i2c1::wtrite_to_display_font10x20(&mut display,
                        core::str::from_utf8(&lbuf[..pos]).unwrap_or("?")
                        , 12);
                }

                // //Rand 2 (y=22): "E0:nnn E1:nnn E2:nnn" primele 3 gate-uri
                // //(cele mai relevante pentru detectie apropiata)
                {
                    let mut pos = 0usize;
                    for i in 0..1usize {
                        let label = [b'E', b'0' + i as u8, b':'];
                        for &c in &label { lbuf[pos] = c; pos += 1; }
                        let se = fmt_u16(frame.energy[i], &mut buf_a);
                        for &c in se.as_bytes() { lbuf[pos] = c; pos += 1; }
                        if i < 2 { lbuf[pos] = b' '; pos += 1; }
                    }
                    let t = core::str::from_utf8(&lbuf[..pos]).unwrap_or("?");
                    pins::utils::i2c1::wtrite_to_display(&mut display,t, 25);
                }


                display.flush().unwrap();
            }

        }


        // pins::utils::gpio_out::led_blink(pc13_out_board_led, clocks.sysclk().to_Hz() / 1);
    }

}














